#!/usr/bin/env python

import os
import csv

#some csv rules :
# Insted of <for column in file_name:> use <for row in file_name:> because reader iterates through the rows, not the columns to my understanding.

#The method os.getcwd() in Python returns the current working directory of a process.
pathName = os.getcwd()
numFiles = []
#os.listdir() method in python is used to get the list of all files and directories in the specified directory. 
#If we don't specify any directory, then list of files and directories in the current working directory will be returned.
fileNames = os.listdir(pathName)
for fileNames in fileNames:
    if fileNames.endswith(".csv"):
        numFiles.append(fileNames)
        
# This code loops through each row and then each column in that row allowing you to view the contents of each cell.
for i in numFiles:
    with open(os.path.join(pathName,i),newline='') as file:
    file = open(os.path.join(pathName, i), "rU")
    csv_reader = csv.reader(file, delimiter=',')
# the below statement will skip the first row
    next(csv_reader)
    for row in csv_reader:
        for column in row:
            print(column['router_A')
           
